import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { FaHome, FaInfoCircle, FaEnvelope } from "react-icons/fa";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Side Nav with Logo */}
        <div className="fixed top-0 left-0 w-50 h-screen bg-gray-500 text-white z-10">
          <Link
            href="/"
            className="h-14 flex items-center px-4 bg-pink-600 text-xl font-bold"
          >
            MyApp Logo
          </Link>
          <nav className="p-2 space-y-2">
            <Link
              href="/component/home"
              className="flex items-center gap-2 bg-blue-500 hover:bg-blue-200 text-white-800 px-4 py-2 rounded"
            >
              <FaHome />
              Home
            </Link>

            <Link
              href="/component/about"
              className="flex items-center gap-2 bg-blue-500 hover:bg-blue-200 text-white-800 px-4 py-2 rounded"
            >
              <FaInfoCircle />
              About
            </Link>

            <Link
              href="/component/contact"
              className="flex items-center gap-2 bg-blue-500 hover:bg-blue-200 text-white-800 px-4 py-2 rounded"
            >
              <FaEnvelope />
              Contact
            </Link>
          </nav>
        </div>

        {/* Top Nav */}
        <nav className="fixed top-0 left-50 right-0 h-14 bg-blue-600 text-white shadow z-10 flex items-center px-6">
          {/* <span className="text-lg">Top Navigation</span> */}
        </nav>

        {/* Page Content */}
        <main className="ml-50 mt-14 p-6 bg-gray-100 min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
